name: build-simbody-wasm

# syntax https://help.github.com/en/articles/workflow-syntax-for-github-actions
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build-wasm:
    name: Simbody WASM Library Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Simbody
        uses: actions/checkout@v4
        with:
          repository: simbody/simbody
          path: 'simbody'

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: '3.1.51'

      - name: Build Simbody (Library Only)
        run: |
          mkdir build_wasm
          cd build_wasm
          
          # FIX: We remove -DBUILD_USING_OTHER_LAPACK=ON. 
          # Instead, we set the LAPACK/BLAS variables to empty strings 
          # to prevent the "unable to find -lON" error.
          
          emcmake cmake ../simbody \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_TOOLCHAIN_FILE=$EMSDK/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake \
            -DBUILD_VISUALIZER=OFF \
            -DBUILD_TESTING=OFF \
            -DBUILD_EXAMPLES=OFF \
            -DLAPACK_LIBRARIES="" \
            -DBLAS_LIBRARIES="" \
            -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/simbody-wasm-install \
            -DCMAKE_CXX_FLAGS="-fexceptions -s DISABLE_EXCEPTION_CATCHING=0 -s ALLOW_MEMORY_GROWTH=1 -s ERROR_ON_UNDEFINED_SYMBOLS=0"
            
          emmake make -j$(nproc)
          emmake make install

      - name: Upload Simbody Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: simbody-wasm-library
          path: simbody-wasm-install/
